# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: symbolprice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='symbolprice.proto',
  package='symbol_price_scraper.symbol_price_scraper.protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11symbolprice.proto\x12\x32symbol_price_scraper.symbol_price_scraper.protobuf\"\xbe\x01\n\x0bSymbolPrice\x12\r\n\x05price\x18\x01 \x01(\t\x12V\n\x06symbol\x18\x02 \x01(\x0e\x32\x46.symbol_price_scraper.symbol_price_scraper.protobuf.SymbolPrice.Symbol\x12\x0c\n\x04unit\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\",\n\x06Symbol\x12\x08\n\x04Gold\x10\x00\x12\n\n\x06Silver\x10\x01\x12\x0c\n\x08Platinum\x10\x02\x62\x06proto3')
)



_SYMBOLPRICE_SYMBOL = _descriptor.EnumDescriptor(
  name='Symbol',
  full_name='symbol_price_scraper.symbol_price_scraper.protobuf.SymbolPrice.Symbol',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Gold', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Silver', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Platinum', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=220,
  serialized_end=264,
)
_sym_db.RegisterEnumDescriptor(_SYMBOLPRICE_SYMBOL)


_SYMBOLPRICE = _descriptor.Descriptor(
  name='SymbolPrice',
  full_name='symbol_price_scraper.symbol_price_scraper.protobuf.SymbolPrice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='price', full_name='symbol_price_scraper.symbol_price_scraper.protobuf.SymbolPrice.price', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='symbol_price_scraper.symbol_price_scraper.protobuf.SymbolPrice.symbol', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='symbol_price_scraper.symbol_price_scraper.protobuf.SymbolPrice.unit', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='symbol_price_scraper.symbol_price_scraper.protobuf.SymbolPrice.time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SYMBOLPRICE_SYMBOL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=264,
)

_SYMBOLPRICE.fields_by_name['symbol'].enum_type = _SYMBOLPRICE_SYMBOL
_SYMBOLPRICE_SYMBOL.containing_type = _SYMBOLPRICE
DESCRIPTOR.message_types_by_name['SymbolPrice'] = _SYMBOLPRICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SymbolPrice = _reflection.GeneratedProtocolMessageType('SymbolPrice', (_message.Message,), dict(
  DESCRIPTOR = _SYMBOLPRICE,
  __module__ = 'symbolprice_pb2'
  # @@protoc_insertion_point(class_scope:symbol_price_scraper.symbol_price_scraper.protobuf.SymbolPrice)
  ))
_sym_db.RegisterMessage(SymbolPrice)


# @@protoc_insertion_point(module_scope)
